import React, { useState } from 'react';
import { Company } from '../types';
import { Briefcase, Code, Brain, BookOpen, Calculator, ChevronRight, SlidersHorizontal } from 'lucide-react';

const COMPANIES: Company[] = [
  { id: 'tcs', name: 'TCS', color: 'bg-blue-600', logo: 'T' },
  { id: 'infosys', name: 'Infosys', color: 'bg-blue-500', logo: 'I' },
  { id: 'wipro', name: 'Wipro', color: 'bg-indigo-600', logo: 'W' },
  { id: 'accenture', name: 'Accenture', color: 'bg-purple-600', logo: 'A' },
  { id: 'cognizant', name: 'Cognizant', color: 'bg-cyan-600', logo: 'C' },
  { id: 'capgemini', name: 'Capgemini', color: 'bg-sky-600', logo: 'C' },
];

const MODULES = [
  { id: 'APTITUDE', name: 'Quantitative Aptitude', icon: Calculator, desc: 'Numerical ability & data interpretation' },
  { id: 'LOGICAL', name: 'Logical Reasoning', icon: Brain, desc: 'Patterns, puzzles & analytical thinking' },
  { id: 'VERBAL', name: 'Verbal Ability', icon: BookOpen, desc: 'Grammar, comprehension & vocabulary' },
  { id: 'CODING', name: 'Coding', icon: Code, desc: 'Data structures & algorithms' },
];

interface DashboardProps {
  onStartQuiz: (company: string, section: string, difficulty: string) => void;
  onStartCoding: (company: string, difficulty: string) => void;
}

const Dashboard: React.FC<DashboardProps> = ({ onStartQuiz, onStartCoding }) => {
  const [selectedCompany, setSelectedCompany] = useState<Company | null>(null);
  const [difficulty, setDifficulty] = useState('Medium');

  const handleCompanySelect = (company: Company) => {
    setSelectedCompany(company);
  };

  const handleModuleClick = (moduleId: string) => {
    if (!selectedCompany) return;
    if (moduleId === 'CODING') {
      onStartCoding(selectedCompany.name, difficulty);
    } else {
      onStartQuiz(selectedCompany.name, moduleId, difficulty);
    }
  };

  return (
    <div className="max-w-6xl mx-auto px-2 sm:px-4">
      {/* Hero Section */}
      {!selectedCompany && (
        <div className="text-center py-8 sm:py-12 mb-8 sm:mb-12 animate-in fade-in slide-in-from-bottom-4 duration-700 px-4">
          <h1 className="text-3xl md:text-5xl font-extrabold text-slate-900 mb-6 tracking-tight">
            Crack Your Dream <span className="text-indigo-600">Placement</span>
          </h1>
          <p className="text-base md:text-lg text-slate-600 max-w-2xl mx-auto mb-8">
            AI-powered preparation for top service-based companies. Practice aptitude, reasoning, and coding with real exam patterns generated by Gemini.
          </p>
        </div>
      )}

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 lg:gap-8">
        
        {/* Company Selector */}
        <div className={`lg:col-span-${selectedCompany ? '4' : '12'} transition-all duration-500 ease-in-out`}>
          <h2 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
             <Briefcase className="w-5 h-5 text-indigo-600" />
             Select Target Company
          </h2>
          <div className={`grid ${selectedCompany ? 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-1' : 'grid-cols-1 sm:grid-cols-2 md:grid-cols-3'} gap-3 sm:gap-4`}>
            {COMPANIES.map((company) => (
              <button
                key={company.id}
                onClick={() => handleCompanySelect(company)}
                className={`p-4 rounded-xl border text-left transition-all duration-300 flex items-center gap-4 group relative overflow-hidden ${
                  selectedCompany?.id === company.id 
                    ? 'border-indigo-600 bg-indigo-50 shadow-md ring-1 ring-indigo-600 scale-[1.02]' 
                    : 'border-slate-200 bg-white hover:border-indigo-300 hover:shadow-lg hover:-translate-y-1'
                }`}
              >
                <div className={`w-10 h-10 sm:w-12 sm:h-12 rounded-lg ${company.color} flex items-center justify-center text-white font-bold text-lg sm:text-xl shadow-sm z-10 relative shrink-0`}>
                  {company.logo}
                </div>
                <div className="z-10 relative min-w-0">
                  <h3 className="font-bold text-slate-800 group-hover:text-indigo-700 transition-colors truncate">{company.name}</h3>
                  <p className="text-xs text-slate-500 truncate">Service-Based</p>
                </div>
                {selectedCompany?.id === company.id && <ChevronRight className="ml-auto w-5 h-5 text-indigo-600 z-10 relative shrink-0" />}
                
                {/* Hover Effect Background */}
                <div className="absolute inset-0 bg-gradient-to-r from-transparent via-indigo-50/50 to-transparent translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-1000"></div>
              </button>
            ))}
          </div>
        </div>

        {/* Dynamic Content Area */}
        {selectedCompany && (
          <div className="lg:col-span-8 space-y-6 lg:space-y-8 animate-in fade-in slide-in-from-right-8 duration-500">
            
            {/* Modules Grid */}
            <div className="bg-white/50 backdrop-blur-sm rounded-3xl p-1">
              <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 px-2 gap-4">
                <h3 className="text-xl font-bold text-slate-800 flex items-center gap-2">
                   <span className="bg-indigo-600 text-white w-8 h-8 rounded-lg flex items-center justify-center text-sm shadow-md">
                     {selectedCompany.logo}
                   </span>
                   Start Practicing
                </h3>
                
                {/* Difficulty Selector */}
                <div className="flex items-center gap-2 bg-white px-3 py-1.5 rounded-lg border border-slate-200 shadow-sm w-full sm:w-auto">
                   <SlidersHorizontal className="w-4 h-4 text-slate-400" />
                   <select 
                    value={difficulty} 
                    onChange={(e) => setDifficulty(e.target.value)}
                    className="text-sm font-medium text-slate-700 bg-transparent focus:outline-none cursor-pointer flex-1 sm:flex-none"
                  >
                    <option value="Easy">Easy</option>
                    <option value="Medium">Medium</option>
                    <option value="Hard">Hard</option>
                  </select>
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {MODULES.map((module) => (
                  <button
                    key={module.id}
                    onClick={() => handleModuleClick(module.id)}
                    className="bg-white p-6 rounded-2xl border border-slate-200 hover:border-indigo-500 hover:shadow-xl hover:shadow-indigo-500/10 transition-all duration-300 text-left group relative overflow-hidden hover:-translate-y-1"
                  >
                    <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity transform group-hover:scale-110 duration-500">
                        <module.icon className="w-24 h-24 text-indigo-600" />
                    </div>

                    <div className="relative z-10">
                      <div className="flex items-start justify-between mb-4">
                        <div className="p-3 bg-indigo-50 rounded-xl group-hover:bg-indigo-600 transition-colors duration-300 shadow-sm">
                          <module.icon className="w-6 h-6 text-indigo-600 group-hover:text-white transition-colors duration-300" />
                        </div>
                        <span className="text-xs font-bold tracking-wider bg-slate-100 text-slate-600 px-2.5 py-1 rounded-md group-hover:bg-indigo-50 group-hover:text-indigo-700 transition-colors">
                           {module.id === 'CODING' ? '1 Problem' : '25 Qs'}
                        </span>
                      </div>
                      <h4 className="text-lg font-bold text-slate-900 mb-2 group-hover:text-indigo-700 transition-colors">{module.name}</h4>
                      <p className="text-sm text-slate-500 leading-relaxed max-w-[90%]">{module.desc}</p>
                    </div>
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default Dashboard;